import { Menu } from "./menu.model";

export const verticalMenuItems = [
  // new Menu(1, 'Dashboard', '/app/dashboard', null, 'dashboard', null, false, 0),
  // new Menu(2, 'Radar', '/app/clients', null, 'account_circle', null, false, 0),
  // new Menu(2, 'Radar', '/app/radar1', null, 'account_circle', null, false, 0),
  new Menu(3, "Dashboard", "/app/dashboard", null, "dashboard", null, true, 0),
  new Menu(
    1,
    "SUB Audits",
    "/app/subjective-audits",
    null,
    "find_in_page",
    null,
    false,
    0,
  ),
  new Menu(
    2,
    "OBJ Audits",
    "/app/objective-audits",
    null,
    "find_in_page",
    null,
    false,
    0,
  ),
  new Menu(6, "PRTS", "/app/prts-part", null, "request_quote", null, false, 0),
  //new Menu(5, 'Setup', '/app/setup', null, 'business_center', null, false, 0),
  // new Menu(3, 'Audits', '/app/projects', null, 'business_center', null, false, 0),
  // new Menu(5, 'Setup', '/app/purchase', null, 'request_quote', null, false, 0),
  //new Menu(6, 'Assets', '/app/assets', null, 'engineering', null, false, 0),
  //new Menu(7, 'Vendor Mgmt', '/app/vendor-mgmt', null, 'panorama_fish_eye', null, false, 0),
  //new Menu(8, 'Finance', '/app/finance', null, 'settings_applications', null, false, 0),
  new Menu(4, "Admin", "/app/admin", null, "supervisor_account", null, true, 0),
  new Menu(
    401,
    "Roles & Users",
    "/app/admin/manage-users",
    null,
    "group_add",
    null,
    false,
    4,
  ),
  // new Menu(402, 'Master Data', '/app/admin/master-data/model', null, 'swap_horiz', null, false, 4),
  new Menu(
    403,
    "Lookup Options",
    "/app/admin/lookups",
    null,
    "search",
    null,
    false,
    4,
  ),
  new Menu(
    404,
    "Preferences",
    "/app/admin/settings",
    null,
    "settings_applications",
    null,
    false,
    4,
  ),
  new Menu(
    405,
    "Event Log",
    "/app/admin/event-log",
    null,
    "engineering",
    null,
    false,
    4,
  ),
  new Menu(
    406,
    "Escalation Matrix",
    "/app/admin/escalation",
    null,
    "mail_outline",
    null,
    false,
    4,
  ),
  // new Menu(406, 'Kanban Setup', '/app/admin/kanban-setup', null, 'panorama_fish_eye', null, false, 4),y
  //new Menu(407, 'Event Log', '/app/admin/event-log', null, 'engineering', null, false, 4),
  // new Menu(408, 'Credentials', '/app/admin/credentials',null,'engineering',null,false,4)
  // In horizontalMenuItems
  new Menu(
    2,
    "OBJ Audits",
    "/app/objective-audits",
    null,
    "find_in_page",
    null,
    false,
    0,
    ["/app/setup/subjective/check"], // ← routes that should activate this item
  ),
];

export const horizontalMenuItems = [
  // --- 1. SQA Module Components ---
  new Menu(1, "Dashboard", "/app/sqm/sqmd", null, "dashboard", null, false, 0),
  new Menu(
    2,
    "Process Audit",
    "/app/sqm/process",
    null,
    "assignment_turned_in",
    null,
    false,
    0,
  ),
  new Menu(
    3,
    "Parts Audit",
    "/app/sqm/parts",
    null,
    "handyman",
    null,
    false,
    0,
  ),
  new Menu(
    4,
    "Inspection",
    "/app/sqm/inspection",
    null,
    "fact_check",
    null,
    false,
    0,
  ),

  // --- 2. Setup (Derived from sqm.component.html) ---
  new Menu(
    5,
    "Setup",
    "/app/sqm/process/setup/process-cat",
    null,
    "build",
    null,
    true,
    0,
  ), // Parent Menu
  new Menu(
    501,
    "Process Audit Categories",
    "/app/sqm/process/setup/process-cat",
    null,
    "category",
    null,
    false,
    5,
  ),
  new Menu(
    502,
    "Commodity Master",
    "/app/sqm/process/setup/commodity",
    null,
    "inventory_2",
    null,
    false,
    5,
  ),
  new Menu(
    503,
    "Parts Audit Categories",
    "/app/sqm/parts/setup/parts-cat",
    null,
    "category",
    null,
    false,
    5,
  ),
  new Menu(
    504,
    "Parts Families",
    "/app/sqm/parts/setup/families",
    null,
    "account_tree",
    null,
    false,
    5,
  ),
  new Menu(
    505,
    "Parts Master",
    "/app/sqm/parts/setup/master",
    null,
    "settings",
    null,
    false,
    5,
  ),
  new Menu(
    506,
    "Batch Master",
    "/app/sqm/parts/setup/batchmaster",
    null,
    "view_module",
    null,
    false,
    5,
  ),
  new Menu(
    507,
    "Defects Master",
    "/app/sqm/parts/setup/defectsmaster",
    null,
    "bug_report",
    null,
    false,
    5,
  ),
  new Menu(
    508,
    "Vendor Rating",
    "/app/sqm/parts/setup/vender-rating",
    null,
    "star_rate",
    null,
    false,
    5,
  ),

  // --- 3. Admin (Preserved) ---
  new Menu(6, "Admin", "/app/admin", null, "supervisor_account", null, true, 0),
  new Menu(
    601,
    "Roles & Users",
    "/app/admin/manage-users",
    null,
    "group_add",
    null,
    false,
    6,
  ),
  new Menu(
    602,
    "Departments",
    "/app/admin/departments",
    null,
    "apartment",
    null,
    false,
    6,
  ),
  new Menu(
    603,
    "Lookup Options",
    "/app/admin/lookups",
    null,
    "search",
    null,
    false,
    6,
  ),
  new Menu(
    604,
    "Preferences",
    "/app/admin/settings",
    null,
    "settings_applications",
    null,
    false,
    6,
  ),
  new Menu(
    605,
    "Event Log",
    "/app/admin/event-log",
    null,
    "engineering",
    null,
    false,
    6,
  ),
  new Menu(
    606,
    "Escalation Matrix",
    "/app/admin/escalation",
    null,
    "mail_outline",
    null,
    false,
    6,
  ),
];

export const clientMenuItems = [
  new Menu(
    1,
    "Client",
    "/app/client-login",
    null,
    "account_circle",
    null,
    false,
    0,
  ),
];

export const supplierMenuItems = [
  new Menu(
    1,
    "Dashboard",
    "/app/supplier-login/dashboard", // Updated to point explicitly to the dashboard child route
    null,
    "dashboard",
    null,
    false,
    0,
  ),
  new Menu(
    2,
    "Process Audit", // Fixed the typo here
    "/app/supplier-login/process-audits", // Updated to the process-audits route
    null,
    "assignment_turned_in",
    null,
    false,
    0,
  ),
  new Menu(
    3,
    "Parts Audit",
    "/app/supplier-login/parts-audits", // Updated from /app/sqm/parts
    null,
    "handyman",
    null,
    false,
    0,
  ),
  new Menu(
    4,
    "Inspection",
    "/app/supplier-login/inspection", // Updated from /app/sqm/inspection
    null,
    "fact_check",
    null,
    false,
    0,
  ),
];
